-- MySQL Script generated by MySQL Workbench
-- Mon Sep 21 13:28:47 2026
-- Model: gameDB    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gameDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gameDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gameDB` DEFAULT CHARACTER SET utf8 ;
USE `gameDB` ;

-- -----------------------------------------------------
-- Table `gameDB`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameDB`.`player` (
  `playerID` INT NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `pwHash` VARCHAR(128) NULL,
  `pwSalt` VARCHAR(128) NULL,
  `rank` VARCHAR(45) NULL,
  PRIMARY KEY (`playerID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`castle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameDB`.`castle` (
  `castleID` INT NOT NULL,
  `castleOwnerID` INT NOT NULL,
  `castleName` VARCHAR(45) NULL,
  PRIMARY KEY (`castleID`),
  INDEX `playerID_idx` (`castleOwnerID` ASC) VISIBLE,
  CONSTRAINT `playerID`
    FOREIGN KEY (`castleOwnerID`)
    REFERENCES `gameDB`.`player` (`playerID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`item types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameDB`.`item types` (
  `itemID` INT NOT NULL,
  `itemName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`itemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`castleitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameDB`.`castleitems` (
  `uniqueidentifier` INT NOT NULL AUTO_INCREMENT,
  `castleID` INT NOT NULL,
  `itemID` INT NOT NULL,
  `pos x` FLOAT NOT NULL,
  `pos y` FLOAT NOT NULL,
  `pos z` FLOAT NOT NULL,
  INDEX `castleID_idx` (`castleID` ASC) VISIBLE,
  INDEX `itemID_idx` (`itemID` ASC) VISIBLE,
  PRIMARY KEY (`uniqueidentifier`),
  CONSTRAINT `castleID`
    FOREIGN KEY (`castleID`)
    REFERENCES `gameDB`.`castle` (`castleID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `itemID`
    FOREIGN KEY (`itemID`)
    REFERENCES `gameDB`.`item types` (`itemID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`playerVaults`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameDB`.`playerVaults` (
  `playerID` INT NOT NULL,
  `itemID` INT NULL,
  `itemName` VARCHAR(65) NULL,
  INDEX `playerID_idx` (`playerID` ASC) VISIBLE,
  CONSTRAINT `playerID`
    FOREIGN KEY (`playerID`)
    REFERENCES `gameDB`.`player` (`playerID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`player research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameDB`.`player research` (
  `playerID` INT NOT NULL,
  `skilltreeID` INT NULL,
  INDEX `playerID_idx` (`playerID` ASC) VISIBLE,
  CONSTRAINT `playerID`
    FOREIGN KEY (`playerID`)
    REFERENCES `gameDB`.`player` (`playerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`player weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameDB`.`player weapons` (
  `playerID` INT NOT NULL,
  `weaponID` INT NOT NULL,
  `weaponXP` FLOAT NOT NULL,
  INDEX `playerID_idx` (`playerID` ASC) VISIBLE,
  CONSTRAINT `playerID`
    FOREIGN KEY (`playerID`)
    REFERENCES `gameDB`.`player` (`playerID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'owner' IDENTIFIED BY 'Queenie16&23Queenie16&23';

GRANT ALL ON `gameDB`.* TO 'owner';
GRANT SELECT ON TABLE `gameDB`.* TO 'owner';
GRANT SELECT, INSERT, TRIGGER ON TABLE `gameDB`.* TO 'owner';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `gameDB`.* TO 'owner';
GRANT EXECUTE ON ROUTINE `gameDB`.* TO 'owner';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
